version: '3'

services:
  inspirational-quotes-db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - inspirational-quotes-db:/data/db
  
volumes:
  inspirational-quotes-db: